// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Malsys.Web.Areas.Administration.Controllers
{
    public partial class StatsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected StatsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public StatsController Actions { get { return MVC.Administration.Stats; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Administration";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Stats";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Stats";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Statistics = "Statistics";
            public readonly string Input = "Input";
            public readonly string Logs = "Logs";
            public readonly string SavedInputs = "SavedInputs";
            public readonly string ExportInputs = "ExportInputs";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Statistics = "Statistics";
            public const string Input = "Input";
            public const string Logs = "Logs";
            public const string SavedInputs = "SavedInputs";
            public const string ExportInputs = "ExportInputs";
        }


        static readonly ActionParamsClass_Input s_params_Input = new ActionParamsClass_Input();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Input InputParams { get { return s_params_Input; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Input
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_Logs s_params_Logs = new ActionParamsClass_Logs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Logs LogsParams { get { return s_params_Logs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Logs
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_SavedInputs s_params_SavedInputs = new ActionParamsClass_SavedInputs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SavedInputs SavedInputsParams { get { return s_params_SavedInputs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SavedInputs
        {
            public readonly string page = "page";
        }
        static readonly ActionParamsClass_ExportInputs s_params_ExportInputs = new ActionParamsClass_ExportInputs();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExportInputs ExportInputsParams { get { return s_params_ExportInputs; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExportInputs
        {
            public readonly string published = "published";
            public readonly string deleted = "deleted";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string Input = "Input";
                public readonly string Logs = "Logs";
                public readonly string SavedInputs = "SavedInputs";
                public readonly string Statistics = "Statistics";
            }
            public readonly string Index = "~/Areas/Administration/Views/Stats/Index.cshtml";
            public readonly string Input = "~/Areas/Administration/Views/Stats/Input.cshtml";
            public readonly string Logs = "~/Areas/Administration/Views/Stats/Logs.cshtml";
            public readonly string SavedInputs = "~/Areas/Administration/Views/Stats/SavedInputs.cshtml";
            public readonly string Statistics = "~/Areas/Administration/Views/Stats/Statistics.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_StatsController : Malsys.Web.Areas.Administration.Controllers.StatsController
    {
        public T4MVC_StatsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void StatisticsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Statistics()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Statistics);
            StatisticsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void InputOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Input(int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Input);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            InputOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void LogsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult Logs(int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Logs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            LogsOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void SavedInputsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int page);

        [NonAction]
        public override System.Web.Mvc.ActionResult SavedInputs(int page)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SavedInputs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "page", page);
            SavedInputsOverride(callInfo, page);
            return callInfo;
        }

        [NonAction]
        partial void ExportInputsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, bool? published, bool? deleted);

        [NonAction]
        public override System.Web.Mvc.ActionResult ExportInputs(bool? published, bool? deleted)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExportInputs);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "published", published);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "deleted", deleted);
            ExportInputsOverride(callInfo, published, deleted);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
