// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Malsys.Web.Areas.Documentation.Controllers
{
    public partial class HomeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected HomeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public HomeController Actions { get { return MVC.Documentation.Home; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Documentation";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Home";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Home";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Faq = "Faq";
            public readonly string LsystemFaq = "LsystemFaq";
            public readonly string BasicRewriting = "BasicRewriting";
            public readonly string LsystemSymbols = "LsystemSymbols";
            public readonly string BasicInterpretation = "BasicInterpretation";
            public readonly string ProcessConfigurations = "ProcessConfigurations";
            public readonly string StdLib = "StdLib";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Faq = "Faq";
            public const string LsystemFaq = "LsystemFaq";
            public const string BasicRewriting = "BasicRewriting";
            public const string LsystemSymbols = "LsystemSymbols";
            public const string BasicInterpretation = "BasicInterpretation";
            public const string ProcessConfigurations = "ProcessConfigurations";
            public const string StdLib = "StdLib";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string BasicInterpretation = "BasicInterpretation";
                public readonly string BasicRewriting = "BasicRewriting";
                public readonly string BasicSyntax = "BasicSyntax";
                public readonly string Faq = "Faq";
                public readonly string Index = "Index";
                public readonly string LsystemFaq = "LsystemFaq";
                public readonly string LsystemSymbols = "LsystemSymbols";
                public readonly string ProcessConfigurations = "ProcessConfigurations";
                public readonly string StdLib = "StdLib";
            }
            public readonly string BasicInterpretation = "~/Areas/Documentation/Views/Home/BasicInterpretation.cshtml";
            public readonly string BasicRewriting = "~/Areas/Documentation/Views/Home/BasicRewriting.cshtml";
            public readonly string BasicSyntax = "~/Areas/Documentation/Views/Home/BasicSyntax.cshtml";
            public readonly string Faq = "~/Areas/Documentation/Views/Home/Faq.cshtml";
            public readonly string Index = "~/Areas/Documentation/Views/Home/Index.cshtml";
            public readonly string LsystemFaq = "~/Areas/Documentation/Views/Home/LsystemFaq.cshtml";
            public readonly string LsystemSymbols = "~/Areas/Documentation/Views/Home/LsystemSymbols.cshtml";
            public readonly string ProcessConfigurations = "~/Areas/Documentation/Views/Home/ProcessConfigurations.cshtml";
            public readonly string StdLib = "~/Areas/Documentation/Views/Home/StdLib.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_HomeController : Malsys.Web.Areas.Documentation.Controllers.HomeController
    {
        public T4MVC_HomeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FaqOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Faq()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Faq);
            FaqOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LsystemFaqOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LsystemFaq()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LsystemFaq);
            LsystemFaqOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void BasicRewritingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult BasicRewriting()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BasicRewriting);
            BasicRewritingOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LsystemSymbolsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LsystemSymbols()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LsystemSymbols);
            LsystemSymbolsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void BasicInterpretationOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult BasicInterpretation()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.BasicInterpretation);
            BasicInterpretationOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ProcessConfigurationsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ProcessConfigurations()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProcessConfigurations);
            ProcessConfigurationsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void StdLibOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult StdLib()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.StdLib);
            StdLibOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
