// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Malsys.Web.Areas.Documentation.Controllers
{
    public partial class PredefinedController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PredefinedController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PredefinedController Actions { get { return MVC.Documentation.Predefined; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Documentation";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Predefined";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Predefined";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Constants = "Constants";
            public readonly string Functions = "Functions";
            public readonly string Operators = "Operators";
            public readonly string Components = "Components";
            public readonly string ComponentsLatex = "ComponentsLatex";
            public readonly string Configurations = "Configurations";
            public readonly string ConfigurationsLatex = "ConfigurationsLatex";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Constants = "Constants";
            public const string Functions = "Functions";
            public const string Operators = "Operators";
            public const string Components = "Components";
            public const string ComponentsLatex = "ComponentsLatex";
            public const string Configurations = "Configurations";
            public const string ConfigurationsLatex = "ConfigurationsLatex";
        }


        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ComponentLatexPartial = "ComponentLatexPartial";
                public readonly string Components = "Components";
                public readonly string ComponentsLatex = "ComponentsLatex";
                public readonly string ConfigurationLatexPartial = "ConfigurationLatexPartial";
                public readonly string Configurations = "Configurations";
                public readonly string ConfigurationsLatex = "ConfigurationsLatex";
                public readonly string Constants = "Constants";
                public readonly string Functions = "Functions";
                public readonly string Operators = "Operators";
            }
            public readonly string ComponentLatexPartial = "~/Areas/Documentation/Views/Predefined/ComponentLatexPartial.cshtml";
            public readonly string Components = "~/Areas/Documentation/Views/Predefined/Components.cshtml";
            public readonly string ComponentsLatex = "~/Areas/Documentation/Views/Predefined/ComponentsLatex.cshtml";
            public readonly string ConfigurationLatexPartial = "~/Areas/Documentation/Views/Predefined/ConfigurationLatexPartial.cshtml";
            public readonly string Configurations = "~/Areas/Documentation/Views/Predefined/Configurations.cshtml";
            public readonly string ConfigurationsLatex = "~/Areas/Documentation/Views/Predefined/ConfigurationsLatex.cshtml";
            public readonly string Constants = "~/Areas/Documentation/Views/Predefined/Constants.cshtml";
            public readonly string Functions = "~/Areas/Documentation/Views/Predefined/Functions.cshtml";
            public readonly string Operators = "~/Areas/Documentation/Views/Predefined/Operators.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PredefinedController : Malsys.Web.Areas.Documentation.Controllers.PredefinedController
    {
        public T4MVC_PredefinedController() : base(Dummy.Instance) { }

        [NonAction]
        partial void ConstantsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Constants()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Constants);
            ConstantsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void FunctionsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Functions()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Functions);
            FunctionsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void OperatorsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Operators()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Operators);
            OperatorsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ComponentsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Components()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Components);
            ComponentsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ComponentsLatexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ComponentsLatex()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ComponentsLatex);
            ComponentsLatexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ConfigurationsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Configurations()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Configurations);
            ConfigurationsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void ConfigurationsLatexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ConfigurationsLatex()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ConfigurationsLatex);
            ConfigurationsLatexOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
