
namespace Malsys.SourceCode.Highlighters {
	public enum MarkType {
		Unknown,
		/// <summary>
		/// Artificial mark to be able to get line start and end string using open/close tag functions.
		/// This mark should not be generated by mark collectors.
		/// </summary>
		Line,

		SingleLineComment,
		MultiLineComment,
		DocComment,

		Separator,

		Lsystem,
		LsystemName,
		LsystemBody,

		VariableDefinition,
		VariableName,

		FunctionDefinition,
		FunctionName,

		Parameter,
		ParameterName,
		PatternVarName,

		RewriteRule,
		RrPattern,
		RrLeftCtxt,
		RrRightCtxt,
		RrVariables,
		RrCondition,
		RrReplacement,
		RrProbability,

		Expression,
		ExprFunName,
		ExprConstant,
		ExprVariable,

		Symbol,
		SymbolPattern,
		SymbolExpr,
		Keyword,

		MsgError,
		MsgWarning,
		MsgNotice,
	}
}
