//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("MalsysDbEntities", "FK_InputProcesses_CanonicInputs", "CanonicInput", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Malsys.Web.Entities.CanonicInput), "InputProcess", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Malsys.Web.Entities.InputProcess), true)]
[assembly: EdmRelationshipAttribute("MalsysDbEntities", "FK_Feedbacks_Users", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Malsys.Web.Entities.User), "Feedback", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Malsys.Web.Entities.Feedback), true)]
[assembly: EdmRelationshipAttribute("MalsysDbEntities", "FK_InputProcesses_InputProcesses", "InputProcess", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Malsys.Web.Entities.InputProcess), "InputProcess1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Malsys.Web.Entities.InputProcess), true)]
[assembly: EdmRelationshipAttribute("MalsysDbEntities", "FK_InputProcesses_Users", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Malsys.Web.Entities.User), "InputProcess", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Malsys.Web.Entities.InputProcess), true)]
[assembly: EdmRelationshipAttribute("MalsysDbEntities", "FK_ProcessOutputs_InputProcesses", "InputProcess", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Malsys.Web.Entities.InputProcess), "ProcessOutput", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Malsys.Web.Entities.ProcessOutput), true)]
[assembly: EdmRelationshipAttribute("MalsysDbEntities", "FK_SavedInputs_InputProcesses", "InputProcess", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Malsys.Web.Entities.InputProcess), "SavedInput", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Malsys.Web.Entities.SavedInput), true)]
[assembly: EdmRelationshipAttribute("MalsysDbEntities", "FK_SavedInputs_Users", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Malsys.Web.Entities.User), "SavedInput", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Malsys.Web.Entities.SavedInput), true)]
[assembly: EdmRelationshipAttribute("MalsysDbEntities", "UsersInRoles", "Role", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Malsys.Web.Entities.Role), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Malsys.Web.Entities.User))]

#endregion

namespace Malsys.Web.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MalsysDb : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MalsysDb object using the connection string found in the 'MalsysDb' section of the application configuration file.
        /// </summary>
        public MalsysDb() : base("name=MalsysDb", "MalsysDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MalsysDb object.
        /// </summary>
        public MalsysDb(string connectionString) : base(connectionString, "MalsysDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MalsysDb object.
        /// </summary>
        public MalsysDb(EntityConnection connection) : base(connection, "MalsysDb")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CanonicInput> CanonicInputs
        {
            get
            {
                if ((_CanonicInputs == null))
                {
                    _CanonicInputs = base.CreateObjectSet<CanonicInput>("CanonicInputs");
                }
                return _CanonicInputs;
            }
        }
        private ObjectSet<CanonicInput> _CanonicInputs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Feedback> Feedbacks
        {
            get
            {
                if ((_Feedbacks == null))
                {
                    _Feedbacks = base.CreateObjectSet<Feedback>("Feedbacks");
                }
                return _Feedbacks;
            }
        }
        private ObjectSet<Feedback> _Feedbacks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<InputProcess> InputProcesses
        {
            get
            {
                if ((_InputProcesses == null))
                {
                    _InputProcesses = base.CreateObjectSet<InputProcess>("InputProcesses");
                }
                return _InputProcesses;
            }
        }
        private ObjectSet<InputProcess> _InputProcesses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProcessOutput> ProcessOutputs
        {
            get
            {
                if ((_ProcessOutputs == null))
                {
                    _ProcessOutputs = base.CreateObjectSet<ProcessOutput>("ProcessOutputs");
                }
                return _ProcessOutputs;
            }
        }
        private ObjectSet<ProcessOutput> _ProcessOutputs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Role> Roles
        {
            get
            {
                if ((_Roles == null))
                {
                    _Roles = base.CreateObjectSet<Role>("Roles");
                }
                return _Roles;
            }
        }
        private ObjectSet<Role> _Roles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SavedInput> SavedInputs
        {
            get
            {
                if ((_SavedInputs == null))
                {
                    _SavedInputs = base.CreateObjectSet<SavedInput>("SavedInputs");
                }
                return _SavedInputs;
            }
        }
        private ObjectSet<SavedInput> _SavedInputs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> Users
        {
            get
            {
                if ((_Users == null))
                {
                    _Users = base.CreateObjectSet<User>("Users");
                }
                return _Users;
            }
        }
        private ObjectSet<User> _Users;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CanonicInputs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCanonicInputs(CanonicInput canonicInput)
        {
            base.AddObject("CanonicInputs", canonicInput);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Feedbacks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFeedbacks(Feedback feedback)
        {
            base.AddObject("Feedbacks", feedback);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the InputProcesses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToInputProcesses(InputProcess inputProcess)
        {
            base.AddObject("InputProcesses", inputProcess);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProcessOutputs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProcessOutputs(ProcessOutput processOutput)
        {
            base.AddObject("ProcessOutputs", processOutput);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Roles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRoles(Role role)
        {
            base.AddObject("Roles", role);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SavedInputs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSavedInputs(SavedInput savedInput)
        {
            base.AddObject("SavedInputs", savedInput);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Users EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUsers(User user)
        {
            base.AddObject("Users", user);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MalsysDbEntities", Name="CanonicInput")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CanonicInput : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CanonicInput object.
        /// </summary>
        /// <param name="canonicInputId">Initial value of the CanonicInputId property.</param>
        /// <param name="hash">Initial value of the Hash property.</param>
        /// <param name="source">Initial value of the Source property.</param>
        /// <param name="sourceSize">Initial value of the SourceSize property.</param>
        /// <param name="outputSize">Initial value of the OutputSize property.</param>
        public static CanonicInput CreateCanonicInput(global::System.Int32 canonicInputId, global::System.Byte[] hash, global::System.String source, global::System.Int32 sourceSize, global::System.Int64 outputSize)
        {
            CanonicInput canonicInput = new CanonicInput();
            canonicInput.CanonicInputId = canonicInputId;
            canonicInput.Hash = hash;
            canonicInput.Source = source;
            canonicInput.SourceSize = sourceSize;
            canonicInput.OutputSize = outputSize;
            return canonicInput;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CanonicInputId
        {
            get
            {
                return _CanonicInputId;
            }
            set
            {
                if (_CanonicInputId != value)
                {
                    OnCanonicInputIdChanging(value);
                    ReportPropertyChanging("CanonicInputId");
                    _CanonicInputId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CanonicInputId");
                    OnCanonicInputIdChanged();
                }
            }
        }
        private global::System.Int32 _CanonicInputId;
        partial void OnCanonicInputIdChanging(global::System.Int32 value);
        partial void OnCanonicInputIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Hash
        {
            get
            {
                return StructuralObject.GetValidValue(_Hash);
            }
            set
            {
                OnHashChanging(value);
                ReportPropertyChanging("Hash");
                _Hash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Hash");
                OnHashChanged();
            }
        }
        private global::System.Byte[] _Hash;
        partial void OnHashChanging(global::System.Byte[] value);
        partial void OnHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SourceSize
        {
            get
            {
                return _SourceSize;
            }
            set
            {
                OnSourceSizeChanging(value);
                ReportPropertyChanging("SourceSize");
                _SourceSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SourceSize");
                OnSourceSizeChanged();
            }
        }
        private global::System.Int32 _SourceSize;
        partial void OnSourceSizeChanging(global::System.Int32 value);
        partial void OnSourceSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 OutputSize
        {
            get
            {
                return _OutputSize;
            }
            set
            {
                OnOutputSizeChanging(value);
                ReportPropertyChanging("OutputSize");
                _OutputSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OutputSize");
                OnOutputSizeChanged();
            }
        }
        private global::System.Int64 _OutputSize;
        partial void OnOutputSizeChanging(global::System.Int64 value);
        partial void OnOutputSizeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_InputProcesses_CanonicInputs", "InputProcess")]
        public EntityCollection<InputProcess> InputProcesses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InputProcess>("MalsysDbEntities.FK_InputProcesses_CanonicInputs", "InputProcess");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InputProcess>("MalsysDbEntities.FK_InputProcesses_CanonicInputs", "InputProcess", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MalsysDbEntities", Name="Feedback")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Feedback : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Feedback object.
        /// </summary>
        /// <param name="feedbackId">Initial value of the FeedbackId property.</param>
        /// <param name="subject">Initial value of the Subject property.</param>
        /// <param name="submitDate">Initial value of the SubmitDate property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="isNew">Initial value of the IsNew property.</param>
        public static Feedback CreateFeedback(global::System.Int32 feedbackId, global::System.String subject, global::System.DateTime submitDate, global::System.String message, global::System.Boolean isNew)
        {
            Feedback feedback = new Feedback();
            feedback.FeedbackId = feedbackId;
            feedback.Subject = subject;
            feedback.SubmitDate = submitDate;
            feedback.Message = message;
            feedback.IsNew = isNew;
            return feedback;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FeedbackId
        {
            get
            {
                return _FeedbackId;
            }
            set
            {
                if (_FeedbackId != value)
                {
                    OnFeedbackIdChanging(value);
                    ReportPropertyChanging("FeedbackId");
                    _FeedbackId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FeedbackId");
                    OnFeedbackIdChanged();
                }
            }
        }
        private global::System.Int32 _FeedbackId;
        partial void OnFeedbackIdChanging(global::System.Int32 value);
        partial void OnFeedbackIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SubmitDate
        {
            get
            {
                return _SubmitDate;
            }
            set
            {
                OnSubmitDateChanging(value);
                ReportPropertyChanging("SubmitDate");
                _SubmitDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubmitDate");
                OnSubmitDateChanged();
            }
        }
        private global::System.DateTime _SubmitDate;
        partial void OnSubmitDateChanging(global::System.DateTime value);
        partial void OnSubmitDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsNew
        {
            get
            {
                return _IsNew;
            }
            set
            {
                OnIsNewChanging(value);
                ReportPropertyChanging("IsNew");
                _IsNew = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNew");
                OnIsNewChanged();
            }
        }
        private global::System.Boolean _IsNew;
        partial void OnIsNewChanging(global::System.Boolean value);
        partial void OnIsNewChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_Feedbacks_Users", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MalsysDbEntities.FK_Feedbacks_Users", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MalsysDbEntities.FK_Feedbacks_Users", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MalsysDbEntities.FK_Feedbacks_Users", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("MalsysDbEntities.FK_Feedbacks_Users", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MalsysDbEntities", Name="InputProcess")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class InputProcess : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new InputProcess object.
        /// </summary>
        /// <param name="inputProcessId">Initial value of the InputProcessId property.</param>
        /// <param name="canonicInputId">Initial value of the CanonicInputId property.</param>
        /// <param name="processDate">Initial value of the ProcessDate property.</param>
        /// <param name="duration">Initial value of the Duration property.</param>
        public static InputProcess CreateInputProcess(global::System.Int32 inputProcessId, global::System.Int32 canonicInputId, global::System.DateTime processDate, global::System.Int64 duration)
        {
            InputProcess inputProcess = new InputProcess();
            inputProcess.InputProcessId = inputProcessId;
            inputProcess.CanonicInputId = canonicInputId;
            inputProcess.ProcessDate = processDate;
            inputProcess.Duration = duration;
            return inputProcess;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InputProcessId
        {
            get
            {
                return _InputProcessId;
            }
            set
            {
                if (_InputProcessId != value)
                {
                    OnInputProcessIdChanging(value);
                    ReportPropertyChanging("InputProcessId");
                    _InputProcessId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("InputProcessId");
                    OnInputProcessIdChanged();
                }
            }
        }
        private global::System.Int32 _InputProcessId;
        partial void OnInputProcessIdChanging(global::System.Int32 value);
        partial void OnInputProcessIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentInputProcessId
        {
            get
            {
                return _ParentInputProcessId;
            }
            set
            {
                OnParentInputProcessIdChanging(value);
                ReportPropertyChanging("ParentInputProcessId");
                _ParentInputProcessId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentInputProcessId");
                OnParentInputProcessIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentInputProcessId;
        partial void OnParentInputProcessIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentInputProcessIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CanonicInputId
        {
            get
            {
                return _CanonicInputId;
            }
            set
            {
                OnCanonicInputIdChanging(value);
                ReportPropertyChanging("CanonicInputId");
                _CanonicInputId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CanonicInputId");
                OnCanonicInputIdChanged();
            }
        }
        private global::System.Int32 _CanonicInputId;
        partial void OnCanonicInputIdChanging(global::System.Int32 value);
        partial void OnCanonicInputIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private Nullable<global::System.Int32> _UserId;
        partial void OnUserIdChanging(Nullable<global::System.Int32> value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ProcessDate
        {
            get
            {
                return _ProcessDate;
            }
            set
            {
                OnProcessDateChanging(value);
                ReportPropertyChanging("ProcessDate");
                _ProcessDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProcessDate");
                OnProcessDateChanged();
            }
        }
        private global::System.DateTime _ProcessDate;
        partial void OnProcessDateChanging(global::System.DateTime value);
        partial void OnProcessDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private global::System.Int64 _Duration;
        partial void OnDurationChanging(global::System.Int64 value);
        partial void OnDurationChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_InputProcesses_CanonicInputs", "CanonicInput")]
        public CanonicInput CanonicInput
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CanonicInput>("MalsysDbEntities.FK_InputProcesses_CanonicInputs", "CanonicInput").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CanonicInput>("MalsysDbEntities.FK_InputProcesses_CanonicInputs", "CanonicInput").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CanonicInput> CanonicInputReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CanonicInput>("MalsysDbEntities.FK_InputProcesses_CanonicInputs", "CanonicInput");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CanonicInput>("MalsysDbEntities.FK_InputProcesses_CanonicInputs", "CanonicInput", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_InputProcesses_InputProcesses", "InputProcess1")]
        public EntityCollection<InputProcess> InputProcesses1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InputProcess>("MalsysDbEntities.FK_InputProcesses_InputProcesses", "InputProcess1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InputProcess>("MalsysDbEntities.FK_InputProcesses_InputProcesses", "InputProcess1", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_InputProcesses_InputProcesses", "InputProcess")]
        public InputProcess InputProcess1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InputProcess>("MalsysDbEntities.FK_InputProcesses_InputProcesses", "InputProcess").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InputProcess>("MalsysDbEntities.FK_InputProcesses_InputProcesses", "InputProcess").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<InputProcess> InputProcess1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InputProcess>("MalsysDbEntities.FK_InputProcesses_InputProcesses", "InputProcess");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<InputProcess>("MalsysDbEntities.FK_InputProcesses_InputProcesses", "InputProcess", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_InputProcesses_Users", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MalsysDbEntities.FK_InputProcesses_Users", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MalsysDbEntities.FK_InputProcesses_Users", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MalsysDbEntities.FK_InputProcesses_Users", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("MalsysDbEntities.FK_InputProcesses_Users", "User", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_ProcessOutputs_InputProcesses", "ProcessOutput")]
        public EntityCollection<ProcessOutput> ProcessOutputs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProcessOutput>("MalsysDbEntities.FK_ProcessOutputs_InputProcesses", "ProcessOutput");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProcessOutput>("MalsysDbEntities.FK_ProcessOutputs_InputProcesses", "ProcessOutput", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_SavedInputs_InputProcesses", "SavedInput")]
        public EntityCollection<SavedInput> SavedInputs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SavedInput>("MalsysDbEntities.FK_SavedInputs_InputProcesses", "SavedInput");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SavedInput>("MalsysDbEntities.FK_SavedInputs_InputProcesses", "SavedInput", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MalsysDbEntities", Name="ProcessOutput")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProcessOutput : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProcessOutput object.
        /// </summary>
        /// <param name="processOutputId">Initial value of the ProcessOutputId property.</param>
        /// <param name="inputProcessId">Initial value of the InputProcessId property.</param>
        /// <param name="fileName">Initial value of the FileName property.</param>
        /// <param name="creationDate">Initial value of the CreationDate property.</param>
        /// <param name="lastOpenDate">Initial value of the LastOpenDate property.</param>
        public static ProcessOutput CreateProcessOutput(global::System.Int32 processOutputId, global::System.Int32 inputProcessId, global::System.String fileName, global::System.DateTime creationDate, global::System.DateTime lastOpenDate)
        {
            ProcessOutput processOutput = new ProcessOutput();
            processOutput.ProcessOutputId = processOutputId;
            processOutput.InputProcessId = inputProcessId;
            processOutput.FileName = fileName;
            processOutput.CreationDate = creationDate;
            processOutput.LastOpenDate = lastOpenDate;
            return processOutput;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProcessOutputId
        {
            get
            {
                return _ProcessOutputId;
            }
            set
            {
                if (_ProcessOutputId != value)
                {
                    OnProcessOutputIdChanging(value);
                    ReportPropertyChanging("ProcessOutputId");
                    _ProcessOutputId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProcessOutputId");
                    OnProcessOutputIdChanged();
                }
            }
        }
        private global::System.Int32 _ProcessOutputId;
        partial void OnProcessOutputIdChanging(global::System.Int32 value);
        partial void OnProcessOutputIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 InputProcessId
        {
            get
            {
                return _InputProcessId;
            }
            set
            {
                OnInputProcessIdChanging(value);
                ReportPropertyChanging("InputProcessId");
                _InputProcessId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("InputProcessId");
                OnInputProcessIdChanged();
            }
        }
        private global::System.Int32 _InputProcessId;
        partial void OnInputProcessIdChanging(global::System.Int32 value);
        partial void OnInputProcessIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreationDate
        {
            get
            {
                return _CreationDate;
            }
            set
            {
                OnCreationDateChanging(value);
                ReportPropertyChanging("CreationDate");
                _CreationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreationDate");
                OnCreationDateChanged();
            }
        }
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastOpenDate
        {
            get
            {
                return _LastOpenDate;
            }
            set
            {
                OnLastOpenDateChanging(value);
                ReportPropertyChanging("LastOpenDate");
                _LastOpenDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastOpenDate");
                OnLastOpenDateChanged();
            }
        }
        private global::System.DateTime _LastOpenDate;
        partial void OnLastOpenDateChanging(global::System.DateTime value);
        partial void OnLastOpenDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_ProcessOutputs_InputProcesses", "InputProcess")]
        public InputProcess InputProcess
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InputProcess>("MalsysDbEntities.FK_ProcessOutputs_InputProcesses", "InputProcess").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InputProcess>("MalsysDbEntities.FK_ProcessOutputs_InputProcesses", "InputProcess").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<InputProcess> InputProcessReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InputProcess>("MalsysDbEntities.FK_ProcessOutputs_InputProcesses", "InputProcess");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<InputProcess>("MalsysDbEntities.FK_ProcessOutputs_InputProcesses", "InputProcess", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MalsysDbEntities", Name="Role")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Role : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Role object.
        /// </summary>
        /// <param name="roleId">Initial value of the RoleId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="nameLowercase">Initial value of the NameLowercase property.</param>
        public static Role CreateRole(global::System.Int32 roleId, global::System.String name, global::System.String nameLowercase)
        {
            Role role = new Role();
            role.RoleId = roleId;
            role.Name = name;
            role.NameLowercase = nameLowercase;
            return role;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleId
        {
            get
            {
                return _RoleId;
            }
            set
            {
                if (_RoleId != value)
                {
                    OnRoleIdChanging(value);
                    ReportPropertyChanging("RoleId");
                    _RoleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleId");
                    OnRoleIdChanged();
                }
            }
        }
        private global::System.Int32 _RoleId;
        partial void OnRoleIdChanging(global::System.Int32 value);
        partial void OnRoleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NameLowercase
        {
            get
            {
                return _NameLowercase;
            }
            set
            {
                OnNameLowercaseChanging(value);
                ReportPropertyChanging("NameLowercase");
                _NameLowercase = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NameLowercase");
                OnNameLowercaseChanged();
            }
        }
        private global::System.String _NameLowercase;
        partial void OnNameLowercaseChanging(global::System.String value);
        partial void OnNameLowercaseChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "UsersInRoles", "User")]
        public EntityCollection<User> Users
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("MalsysDbEntities.UsersInRoles", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("MalsysDbEntities.UsersInRoles", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MalsysDbEntities", Name="SavedInput")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SavedInput : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SavedInput object.
        /// </summary>
        /// <param name="savedInputId">Initial value of the SavedInputId property.</param>
        /// <param name="randomId">Initial value of the RandomId property.</param>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        /// <param name="source">Initial value of the Source property.</param>
        /// <param name="sourceSize">Initial value of the SourceSize property.</param>
        /// <param name="outputSize">Initial value of the OutputSize property.</param>
        /// <param name="duration">Initial value of the Duration property.</param>
        /// <param name="views">Initial value of the Views property.</param>
        public static SavedInput CreateSavedInput(global::System.Int32 savedInputId, global::System.String randomId, global::System.Int32 userId, global::System.DateTime date, global::System.String source, global::System.Int32 sourceSize, global::System.Int64 outputSize, global::System.Int64 duration, global::System.Int32 views)
        {
            SavedInput savedInput = new SavedInput();
            savedInput.SavedInputId = savedInputId;
            savedInput.RandomId = randomId;
            savedInput.UserId = userId;
            savedInput.Date = date;
            savedInput.Source = source;
            savedInput.SourceSize = sourceSize;
            savedInput.OutputSize = outputSize;
            savedInput.Duration = duration;
            savedInput.Views = views;
            return savedInput;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SavedInputId
        {
            get
            {
                return _SavedInputId;
            }
            set
            {
                if (_SavedInputId != value)
                {
                    OnSavedInputIdChanging(value);
                    ReportPropertyChanging("SavedInputId");
                    _SavedInputId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SavedInputId");
                    OnSavedInputIdChanged();
                }
            }
        }
        private global::System.Int32 _SavedInputId;
        partial void OnSavedInputIdChanging(global::System.Int32 value);
        partial void OnSavedInputIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RandomId
        {
            get
            {
                return _RandomId;
            }
            set
            {
                OnRandomIdChanging(value);
                ReportPropertyChanging("RandomId");
                _RandomId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RandomId");
                OnRandomIdChanged();
            }
        }
        private global::System.String _RandomId;
        partial void OnRandomIdChanging(global::System.String value);
        partial void OnRandomIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentInputProcessId
        {
            get
            {
                return _ParentInputProcessId;
            }
            set
            {
                OnParentInputProcessIdChanging(value);
                ReportPropertyChanging("ParentInputProcessId");
                _ParentInputProcessId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentInputProcessId");
                OnParentInputProcessIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentInputProcessId;
        partial void OnParentInputProcessIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentInputProcessIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SourceSize
        {
            get
            {
                return _SourceSize;
            }
            set
            {
                OnSourceSizeChanging(value);
                ReportPropertyChanging("SourceSize");
                _SourceSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SourceSize");
                OnSourceSizeChanged();
            }
        }
        private global::System.Int32 _SourceSize;
        partial void OnSourceSizeChanging(global::System.Int32 value);
        partial void OnSourceSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 OutputSize
        {
            get
            {
                return _OutputSize;
            }
            set
            {
                OnOutputSizeChanging(value);
                ReportPropertyChanging("OutputSize");
                _OutputSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OutputSize");
                OnOutputSizeChanged();
            }
        }
        private global::System.Int64 _OutputSize;
        partial void OnOutputSizeChanging(global::System.Int64 value);
        partial void OnOutputSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private global::System.Int64 _Duration;
        partial void OnDurationChanging(global::System.Int64 value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Views
        {
            get
            {
                return _Views;
            }
            set
            {
                OnViewsChanging(value);
                ReportPropertyChanging("Views");
                _Views = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Views");
                OnViewsChanged();
            }
        }
        private global::System.Int32 _Views;
        partial void OnViewsChanging(global::System.Int32 value);
        partial void OnViewsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_SavedInputs_InputProcesses", "InputProcess")]
        public InputProcess InputProcess
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InputProcess>("MalsysDbEntities.FK_SavedInputs_InputProcesses", "InputProcess").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InputProcess>("MalsysDbEntities.FK_SavedInputs_InputProcesses", "InputProcess").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<InputProcess> InputProcessReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<InputProcess>("MalsysDbEntities.FK_SavedInputs_InputProcesses", "InputProcess");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<InputProcess>("MalsysDbEntities.FK_SavedInputs_InputProcesses", "InputProcess", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_SavedInputs_Users", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MalsysDbEntities.FK_SavedInputs_Users", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MalsysDbEntities.FK_SavedInputs_Users", "User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("MalsysDbEntities.FK_SavedInputs_Users", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("MalsysDbEntities.FK_SavedInputs_Users", "User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MalsysDbEntities", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="userId">Initial value of the UserId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="nameLowercase">Initial value of the NameLowercase property.</param>
        /// <param name="passwordHash">Initial value of the PasswordHash property.</param>
        /// <param name="passwordSalt">Initial value of the PasswordSalt property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="registrationDate">Initial value of the RegistrationDate property.</param>
        /// <param name="lastLoginDate">Initial value of the LastLoginDate property.</param>
        /// <param name="lastActivityDate">Initial value of the LastActivityDate property.</param>
        /// <param name="lastPwdChangeDate">Initial value of the LastPwdChangeDate property.</param>
        public static User CreateUser(global::System.Int32 userId, global::System.String name, global::System.String nameLowercase, global::System.Byte[] passwordHash, global::System.Byte[] passwordSalt, global::System.String email, global::System.DateTime registrationDate, global::System.DateTime lastLoginDate, global::System.DateTime lastActivityDate, global::System.DateTime lastPwdChangeDate)
        {
            User user = new User();
            user.UserId = userId;
            user.Name = name;
            user.NameLowercase = nameLowercase;
            user.PasswordHash = passwordHash;
            user.PasswordSalt = passwordSalt;
            user.Email = email;
            user.RegistrationDate = registrationDate;
            user.LastLoginDate = lastLoginDate;
            user.LastActivityDate = lastActivityDate;
            user.LastPwdChangeDate = lastPwdChangeDate;
            return user;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NameLowercase
        {
            get
            {
                return _NameLowercase;
            }
            set
            {
                OnNameLowercaseChanging(value);
                ReportPropertyChanging("NameLowercase");
                _NameLowercase = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NameLowercase");
                OnNameLowercaseChanged();
            }
        }
        private global::System.String _NameLowercase;
        partial void OnNameLowercaseChanging(global::System.String value);
        partial void OnNameLowercaseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] PasswordHash
        {
            get
            {
                return StructuralObject.GetValidValue(_PasswordHash);
            }
            set
            {
                OnPasswordHashChanging(value);
                ReportPropertyChanging("PasswordHash");
                _PasswordHash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PasswordHash");
                OnPasswordHashChanged();
            }
        }
        private global::System.Byte[] _PasswordHash;
        partial void OnPasswordHashChanging(global::System.Byte[] value);
        partial void OnPasswordHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] PasswordSalt
        {
            get
            {
                return StructuralObject.GetValidValue(_PasswordSalt);
            }
            set
            {
                OnPasswordSaltChanging(value);
                ReportPropertyChanging("PasswordSalt");
                _PasswordSalt = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PasswordSalt");
                OnPasswordSaltChanged();
            }
        }
        private global::System.Byte[] _PasswordSalt;
        partial void OnPasswordSaltChanging(global::System.Byte[] value);
        partial void OnPasswordSaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RegistrationDate
        {
            get
            {
                return _RegistrationDate;
            }
            set
            {
                OnRegistrationDateChanging(value);
                ReportPropertyChanging("RegistrationDate");
                _RegistrationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistrationDate");
                OnRegistrationDateChanged();
            }
        }
        private global::System.DateTime _RegistrationDate;
        partial void OnRegistrationDateChanging(global::System.DateTime value);
        partial void OnRegistrationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastLoginDate
        {
            get
            {
                return _LastLoginDate;
            }
            set
            {
                OnLastLoginDateChanging(value);
                ReportPropertyChanging("LastLoginDate");
                _LastLoginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginDate");
                OnLastLoginDateChanged();
            }
        }
        private global::System.DateTime _LastLoginDate;
        partial void OnLastLoginDateChanging(global::System.DateTime value);
        partial void OnLastLoginDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastActivityDate
        {
            get
            {
                return _LastActivityDate;
            }
            set
            {
                OnLastActivityDateChanging(value);
                ReportPropertyChanging("LastActivityDate");
                _LastActivityDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastActivityDate");
                OnLastActivityDateChanged();
            }
        }
        private global::System.DateTime _LastActivityDate;
        partial void OnLastActivityDateChanging(global::System.DateTime value);
        partial void OnLastActivityDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastPwdChangeDate
        {
            get
            {
                return _LastPwdChangeDate;
            }
            set
            {
                OnLastPwdChangeDateChanging(value);
                ReportPropertyChanging("LastPwdChangeDate");
                _LastPwdChangeDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastPwdChangeDate");
                OnLastPwdChangeDateChanged();
            }
        }
        private global::System.DateTime _LastPwdChangeDate;
        partial void OnLastPwdChangeDateChanging(global::System.DateTime value);
        partial void OnLastPwdChangeDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_Feedbacks_Users", "Feedback")]
        public EntityCollection<Feedback> Feedbacks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Feedback>("MalsysDbEntities.FK_Feedbacks_Users", "Feedback");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Feedback>("MalsysDbEntities.FK_Feedbacks_Users", "Feedback", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_InputProcesses_Users", "InputProcess")]
        public EntityCollection<InputProcess> InputProcesses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<InputProcess>("MalsysDbEntities.FK_InputProcesses_Users", "InputProcess");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<InputProcess>("MalsysDbEntities.FK_InputProcesses_Users", "InputProcess", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "FK_SavedInputs_Users", "SavedInput")]
        public EntityCollection<SavedInput> SavedInputs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SavedInput>("MalsysDbEntities.FK_SavedInputs_Users", "SavedInput");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SavedInput>("MalsysDbEntities.FK_SavedInputs_Users", "SavedInput", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("MalsysDbEntities", "UsersInRoles", "Role")]
        public EntityCollection<Role> Roles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Role>("MalsysDbEntities.UsersInRoles", "Role");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Role>("MalsysDbEntities.UsersInRoles", "Role", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
