/* Exported by SQL Server Management Studio */
/****** Object:  Table [dbo].[Users]    Script Date: 04/12/2012 17:35:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Users](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](32) NOT NULL,
	[NameLowercase] [nvarchar](32) NOT NULL,
	[PasswordHash] [binary](64) NOT NULL,
	[PasswordSalt] [binary](64) NOT NULL,
	[Email] [nvarchar](max) NOT NULL,
	[RegistrationDate] [datetime] NOT NULL,
	[LastLoginDate] [datetime] NOT NULL,
	[LastActivityDate] [datetime] NOT NULL,
	[LastPwdChangeDate] [datetime] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED
(
	[UserId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Tags]    Script Date: 04/13/2012 17:34:38 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tags](
	[TagId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](32) NOT NULL,
	[NameLowercase] [nvarchar](32) NOT NULL,
	[Description] [nvarchar](max) NULL,
 CONSTRAINT [PK_Tags] PRIMARY KEY CLUSTERED
(
	[TagId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CanonicInputs]    Script Date: 04/12/2012 17:35:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[CanonicInputs](
	[CanonicInputId] [int] IDENTITY(1,1) NOT NULL,
	[Hash] [binary](16) NOT NULL,
	[SourceCode] [nvarchar](max) NOT NULL,
	[SourceSize] [int] NOT NULL,
	[OutputSize] [bigint] NOT NULL,
 CONSTRAINT [PK_CanonicLsystems] PRIMARY KEY CLUSTERED
(
	[CanonicInputId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'For fast search of the same inputs.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CanonicInputs', @level2type=N'COLUMN',@level2name=N'Hash'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The size in bytes of this input.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CanonicInputs', @level2type=N'COLUMN',@level2name=N'SourceSize'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The size in bytes of output generated by this source.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'CanonicInputs', @level2type=N'COLUMN',@level2name=N'OutputSize'
GO
/****** Object:  Table [dbo].[Roles]    Script Date: 04/12/2012 17:35:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Roles](
	[RoleId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](32) NOT NULL,
	[NameLowercase] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED
(
	[RoleId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[InputProcesses]    Script Date: 04/12/2012 17:35:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[InputProcesses](
	[InputProcessId] [int] IDENTITY(1,1) NOT NULL,
	[ParentInputProcessId] [int] NULL,
	[ChainLength] [int] NOT NULL,
	[CanonicInputId] [int] NOT NULL,
	[UserId] [int] NULL,
	[ProcessDate] [datetime] NOT NULL,
	[Duration] [bigint] NOT NULL,
 CONSTRAINT [PK_LsystemProcesses] PRIMARY KEY CLUSTERED
(
	[InputProcessId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The length of parent chain. Number of consecutively processed inputs till this input. Higher numbers means more iterations of development of input.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'InputProcesses', @level2type=N'COLUMN',@level2name=N'ChainLength'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Duration of compilation and processing of input in ticks.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'InputProcesses', @level2type=N'COLUMN',@level2name=N'Duration'
GO
/****** Object:  Table [dbo].[Feedbacks]    Script Date: 04/12/2012 17:35:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Feedbacks](
	[FeedbackId] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[Subject] [nvarchar](max) NOT NULL,
	[SubmitDate] [datetime] NOT NULL,
	[Email] [nvarchar](max) NULL,
	[Message] [nvarchar](max) NOT NULL,
	[IsNew] [bit] NOT NULL,
 CONSTRAINT [PK_Feedbacks] PRIMARY KEY CLUSTERED
(
	[FeedbackId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UsersInRoles]    Script Date: 04/12/2012 17:35:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UsersInRoles](
	[UserId] [int] NOT NULL,
	[RoleId] [int] NOT NULL,
 CONSTRAINT [PK_UsersInRoles] PRIMARY KEY NONCLUSTERED
(
	[UserId] ASC,
	[RoleId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SavedInputs]    Script Date: 04/12/2012 17:35:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[SavedInputs](
	[SavedInputId] [int] IDENTITY(1,1) NOT NULL,
	[UrlId] [nchar](8) NOT NULL,
	[ParentInputProcessId] [int] NULL,
	[CreationUserId] [int] NOT NULL,
	[CreationDate] [datetime] NOT NULL,
	[EditDate] [datetime] NOT NULL,
	[IsPublished] [bit] NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[PublishName] [nvarchar](32) NULL,
	[Views] [int] NOT NULL,
	[SourceSize] [int] NOT NULL,
	[OutputSize] [bigint] NOT NULL,
	[Duration] [bigint] NOT NULL,
	[MimeType] [nvarchar](32) NULL,
	[SourceCode] [nvarchar](max) NOT NULL,
	[ThumbnailSourceExtension] [nvarchar](max) NULL,
	[Description] [nvarchar](max) NULL,
	[OutputMetadata] [varbinary](max) NULL,
	[OutputThnMetadata] [varbinary](max) NULL,
	[RatingSum] [int] NOT NULL,
	[RatingCount] [int] NOT NULL,
 CONSTRAINT [PK_SavedInputs] PRIMARY KEY CLUSTERED
(
	[SavedInputId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The author.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SavedInputs', @level2type=N'COLUMN',@level2name=N'CreationUserId'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Date of creation.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SavedInputs', @level2type=N'COLUMN',@level2name=N'CreationDate'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Date of last edit.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SavedInputs', @level2type=N'COLUMN',@level2name=N'EditDate'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'True if everybody can view it in gallery. If false only acces is with URl link.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SavedInputs', @level2type=N'COLUMN',@level2name=N'IsPublished'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The size in bytes of this input.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SavedInputs', @level2type=N'COLUMN',@level2name=N'SourceSize'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'The size in bytes of output generated by this source.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SavedInputs', @level2type=N'COLUMN',@level2name=N'OutputSize'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Duration of compilation and processing of input in ticks.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SavedInputs', @level2type=N'COLUMN',@level2name=N'Duration'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Serialized metadata for output.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SavedInputs', @level2type=N'COLUMN',@level2name=N'OutputMetadata'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SavedInputs', @level2type=N'COLUMN',@level2name=N'RatingSum'
GO
/****** Object:  Table [dbo].[ProcessOutputs]    Script Date: 04/12/2012 17:35:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[ProcessOutputs](
	[ProcessOutputId] [int] IDENTITY(1,1) NOT NULL,
	[InputProcessId] [int] NULL,
	[FileName] [nvarchar](64) NOT NULL,
	[CreationDate] [datetime] NOT NULL,
	[LastOpenDate] [datetime] NOT NULL,
	[Metadata] [varbinary](max) NULL,
 CONSTRAINT [PK_ProcessOutputs] PRIMARY KEY CLUSTERED
(
	[ProcessOutputId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Serialized output metadata.' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'ProcessOutputs', @level2type=N'COLUMN',@level2name=N'Metadata'
GO
/****** Object:  Table [dbo].[TaggedSavedInputs]    Script Date: 04/12/2012 17:35:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaggedSavedInputs](
	[SavedInputId] [int] NOT NULL,
	[TagId] [int] NOT NULL,
 CONSTRAINT [PK_TaggedSavedInputs] PRIMARY KEY CLUSTERED
(
	[SavedInputId] ASC,
	[TagId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SavedInputVotes]    Script Date: 04/12/2012 17:35:33 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SavedInputVotes](
	[SavedInputId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	[Rating] [int] NOT NULL,
 CONSTRAINT [PK_SavedInputsVoes_1] PRIMARY KEY CLUSTERED
(
	[SavedInputId] ASC,
	[UserId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  ForeignKey [FK_Feedbacks_Users]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[Feedbacks]  WITH CHECK ADD  CONSTRAINT [FK_Feedbacks_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Feedbacks] CHECK CONSTRAINT [FK_Feedbacks_Users]
GO
/****** Object:  ForeignKey [FK_InputProcesses_CanonicInputs]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[InputProcesses]  WITH CHECK ADD  CONSTRAINT [FK_InputProcesses_CanonicInputs] FOREIGN KEY([CanonicInputId])
REFERENCES [dbo].[CanonicInputs] ([CanonicInputId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[InputProcesses] CHECK CONSTRAINT [FK_InputProcesses_CanonicInputs]
GO
/****** Object:  ForeignKey [FK_InputProcesses_InputProcesses]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[InputProcesses]  WITH CHECK ADD  CONSTRAINT [FK_InputProcesses_InputProcesses] FOREIGN KEY([ParentInputProcessId])
REFERENCES [dbo].[InputProcesses] ([InputProcessId])
GO
ALTER TABLE [dbo].[InputProcesses] CHECK CONSTRAINT [FK_InputProcesses_InputProcesses]
GO
/****** Object:  ForeignKey [FK_InputProcesses_Users]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[InputProcesses]  WITH CHECK ADD  CONSTRAINT [FK_InputProcesses_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[InputProcesses] CHECK CONSTRAINT [FK_InputProcesses_Users]
GO
/****** Object:  ForeignKey [FK_ProcessOutputs_InputProcesses]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[ProcessOutputs]  WITH CHECK ADD  CONSTRAINT [FK_ProcessOutputs_InputProcesses] FOREIGN KEY([InputProcessId])
REFERENCES [dbo].[InputProcesses] ([InputProcessId])
ON UPDATE SET NULL
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[ProcessOutputs] CHECK CONSTRAINT [FK_ProcessOutputs_InputProcesses]
GO
/****** Object:  ForeignKey [FK_SavedInputs_InputProcesses]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[SavedInputs]  WITH CHECK ADD  CONSTRAINT [FK_SavedInputs_InputProcesses] FOREIGN KEY([ParentInputProcessId])
REFERENCES [dbo].[InputProcesses] ([InputProcessId])
ON UPDATE SET NULL
ON DELETE SET NULL
GO
ALTER TABLE [dbo].[SavedInputs] CHECK CONSTRAINT [FK_SavedInputs_InputProcesses]
GO
/****** Object:  ForeignKey [FK_SavedInputs_Users]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[SavedInputs]  WITH CHECK ADD  CONSTRAINT [FK_SavedInputs_Users] FOREIGN KEY([CreationUserId])
REFERENCES [dbo].[Users] ([UserId])
GO
ALTER TABLE [dbo].[SavedInputs] CHECK CONSTRAINT [FK_SavedInputs_Users]
GO
/****** Object:  ForeignKey [FK_SavedInputsVoes_SavedInputs]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[SavedInputVotes]  WITH CHECK ADD  CONSTRAINT [FK_SavedInputsVoes_SavedInputs] FOREIGN KEY([SavedInputId])
REFERENCES [dbo].[SavedInputs] ([SavedInputId])
GO
ALTER TABLE [dbo].[SavedInputVotes] CHECK CONSTRAINT [FK_SavedInputsVoes_SavedInputs]
GO
/****** Object:  ForeignKey [FK_SavedInputsVoes_Users]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[SavedInputVotes]  WITH CHECK ADD  CONSTRAINT [FK_SavedInputsVoes_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[SavedInputVotes] CHECK CONSTRAINT [FK_SavedInputsVoes_Users]
GO
/****** Object:  ForeignKey [FK_TaggedSavedInputs_SavedInputs]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[TaggedSavedInputs]  WITH CHECK ADD  CONSTRAINT [FK_TaggedSavedInputs_SavedInputs] FOREIGN KEY([SavedInputId])
REFERENCES [dbo].[SavedInputs] ([SavedInputId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TaggedSavedInputs] CHECK CONSTRAINT [FK_TaggedSavedInputs_SavedInputs]
GO
/****** Object:  ForeignKey [FK_TaggedSavedInputs_Tags]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[TaggedSavedInputs]  WITH CHECK ADD  CONSTRAINT [FK_TaggedSavedInputs_Tags] FOREIGN KEY([TagId])
REFERENCES [dbo].[Tags] ([TagId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[TaggedSavedInputs] CHECK CONSTRAINT [FK_TaggedSavedInputs_Tags]
GO
/****** Object:  ForeignKey [FK_UsersInRoles_Roles]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[UsersInRoles]  WITH CHECK ADD  CONSTRAINT [FK_UsersInRoles_Roles] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Roles] ([RoleId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UsersInRoles] CHECK CONSTRAINT [FK_UsersInRoles_Roles]
GO
/****** Object:  ForeignKey [FK_UsersInRoles_Users]    Script Date: 04/12/2012 17:35:33 ******/
ALTER TABLE [dbo].[UsersInRoles]  WITH CHECK ADD  CONSTRAINT [FK_UsersInRoles_Users] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UserId])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UsersInRoles] CHECK CONSTRAINT [FK_UsersInRoles_Users]
GO
